# Generated by Django 2.2.6 on 2019-10-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='guests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Guests'),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='property',
            name='roomates',
            field=models.BooleanField(blank=True, null=True, verbose_name='Roomates'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1, verbose_name='Rooms'),
        ),
    ]
