# Generated by Django 2.2.6 on 2019-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20191005_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Url'),
        ),
    ]
